//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBowlingClub.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int Id { get; set; }
        public int LaneId { get; set; }
        public int ClientId { get; set; }
        public int Status { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int PlayersCount { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Lanes Lanes { get; set; }
    }
}
